#!/bin/bash

# update #

# variables #

scripts_list=(
	models-sync
	models-pages
)

# run scripts

for script in ${scripts_list[@]}
do
	bash ${script}
done

# upload changes

git add *

git commit -a -m 'Models update'

git push